version: "3.8"

services:
  repo-updater:
    image: alpine/git
    container_name: repo-updater
    volumes:
      - insyra-code:/app  # 使用卷來儲存 GitHub 儲存庫的內容
    environment:
      - REPO_URL=https://github.com/HazelnutParadise/insyra-website.git
    entrypoint: >
      /bin/sh -c "
      if [ ! -d '/app/.git' ]; then
        git clone $REPO_URL /app;
      else
        cd /app && git pull;
      fi
      sleep 3600;  # 每小時檢查一次
      "

  insyra-website:
    build:
      context: /app  # 使用 repo-updater 服務克隆的代碼作為構建上下文
      dockerfile: /app/Dockerfile
    container_name: insyra-website
    ports:
      - "1234:8080"
    restart: always
    depends_on:
      - repo-updater

volumes:
  insyra-code:
