version: "3.8"

# 2024/10/31 15:32 更新
services:
  insyra-website:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: insyra-website
    ports:
      - "1234:8080"
    restart: always
