version: "3.8"

services:
  insyra-website:
    build:
      context: https://github.com/HazelnutParadise/insyra-website.git
      dockerfile: Dockerfile
    container_name: insyra-website
    ports:
      - "1234:8080"
    restart: always
